[server]
name = "board"
host = ":18093"
port = 18093
logpath = "/data/logs/board/"

[consul]
host = "192.168.200.191:8500"

[redis]
host = "192.168.200.191:6379"
auth = ""
index = 15 
max_idle = 10

[mongo]
host = "127.0.0.1:27017"
#auth = "test:BwUSdSQxtUx@"
auth = ""
database = ["BoardComment", "BoardLike", "BoardSummary"]
