[server]
name = "board"
host = ":18093"
port = 18093
logpath = "/data/logs/board/"

[consul]
host = "192.168.200.191:8500"

[redis]
host = "redis-test.gengxo.ng.0001.use2.cache.amazonaws.com:6379"
auth = ""
index = 1
max_idle = 10

[mongo]
host = "172.31.35.223:20000,172.31.39.42:20000"
auth = "testuser:BwUSdSQxtUx@"
database = ["Board"]
