[server]
name = "board"
host = ":18093"
port = 18093
logpath = "/data/logs/board/"

[logger]
file_path = "/Users/qulei/workspace/src/a.com/go-server/board/logs/logs.log"
max_size = 1024   # 1G
max_backups = 2   # 2 copy
max_age = 20      # 20 days
level = 0         # INFO
compress = false

[consul]
host = "127.0.0.1:8500"

[redis]
host = "127.0.0.1:6379"
auth = ""
index = 15 
max_idle = 10

[mongo]
host = "127.0.0.1:27017"
#auth = "test:BwUSdSQxtUx@"
auth = ""
database = ["BoardComment", "BoardLike", "BoardSummary"]
