[server]
name = "esearch"
host = ":18092"
port = 18092
logpath = "/data/logs/esearch/"

[logger]
file_path = "/Users/qulei/workspace/src/a.com/go-server/esearch/logs/logs.log"
max_size = 1024   # 1G
max_backups = 2   # 2 copy
max_age = 20      # 20 days
level = 0         # INFO
compress = false

[consul]
host = "192.168.200.191:8500"

[elastic]
hosts = ["http://172.31.40.234:9200"]
auth = ""
