[server]
name = "uploader"
host = ":18091"
port = 18091
logpath = "/data/logs/uploader/"

[consul]
host = "192.168.200.191:8500"

[s3]
region = "us-east-2"
acl = "private"
bucket= "test-bucket"

[mysql]
host = "192.168.200.191:3306"
auth = "mysql_user:V3CSDJ3Gtg"
max_idle = 5
max_open = 20
database = ["uploader"]
