[server]
name = "gateway-api"
host = ":8091"
port = 8091

[logger]
file_path = "/Users/qulei/workspace/src/a.com/go-server/gateway-api/logs/logs.log"
max_size = 1024   # 1G
max_backups = 2   # 2 copy
max_age = 20      # 20 days
level = 0         # INFO
compress = false

[grpc]
consul = "192.168.200.191:8500"
services = ["board", "uploader", "esearch"]
