// Code generated by protoc-gen-go. DO NOT EDIT.
// source: uploader.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 文件类型 图片/头像/普通文件
type FileType int32

const (
	FileType_IMAGE  FileType = 0
	FileType_AVATAR FileType = 1
	FileType_FILE   FileType = 2
)

var FileType_name = map[int32]string{
	0: "IMAGE",
	1: "AVATAR",
	2: "FILE",
}
var FileType_value = map[string]int32{
	"IMAGE":  0,
	"AVATAR": 1,
	"FILE":   2,
}

func (x FileType) String() string {
	return proto.EnumName(FileType_name, int32(x))
}
func (FileType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// 文件上传参数
type UploadRequest struct {
	Id    string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Ex    string   `protobuf:"bytes,2,opt,name=ex" json:"ex,omitempty"`
	Typef FileType `protobuf:"varint,3,opt,name=typef,enum=pb.FileType" json:"typef,omitempty"`
	Data  []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *UploadRequest) Reset()                    { *m = UploadRequest{} }
func (m *UploadRequest) String() string            { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()               {}
func (*UploadRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *UploadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UploadRequest) GetEx() string {
	if m != nil {
		return m.Ex
	}
	return ""
}

func (m *UploadRequest) GetTypef() FileType {
	if m != nil {
		return m.Typef
	}
	return FileType_IMAGE
}

func (m *UploadRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 根据文件id拉取文件信息的参数
type FileRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *FileRequest) Reset()                    { *m = FileRequest{} }
func (m *FileRequest) String() string            { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()               {}
func (*FileRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *FileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// 文件信息
type FileInfo struct {
	Id     string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Ex     string   `protobuf:"bytes,2,opt,name=ex" json:"ex,omitempty"`
	Typef  FileType `protobuf:"varint,3,opt,name=typef,enum=pb.FileType" json:"typef,omitempty"`
	Width  int32    `protobuf:"varint,4,opt,name=width" json:"width,omitempty"`
	Height int32    `protobuf:"varint,5,opt,name=height" json:"height,omitempty"`
	Size   int64    `protobuf:"varint,6,opt,name=size" json:"size,omitempty"`
}

func (m *FileInfo) Reset()                    { *m = FileInfo{} }
func (m *FileInfo) String() string            { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()               {}
func (*FileInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *FileInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FileInfo) GetEx() string {
	if m != nil {
		return m.Ex
	}
	return ""
}

func (m *FileInfo) GetTypef() FileType {
	if m != nil {
		return m.Typef
	}
	return FileType_IMAGE
}

func (m *FileInfo) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *FileInfo) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*UploadRequest)(nil), "pb.UploadRequest")
	proto.RegisterType((*FileRequest)(nil), "pb.FileRequest")
	proto.RegisterType((*FileInfo)(nil), "pb.FileInfo")
	proto.RegisterEnum("pb.FileType", FileType_name, FileType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Uploader service

type UploaderClient interface {
	// 文件上传
	Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*FileInfo, error)
	// 获取文件信息
	GetFileInfo(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileInfo, error)
}

type uploaderClient struct {
	cc *grpc.ClientConn
}

func NewUploaderClient(cc *grpc.ClientConn) UploaderClient {
	return &uploaderClient{cc}
}

func (c *uploaderClient) Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*FileInfo, error) {
	out := new(FileInfo)
	err := grpc.Invoke(ctx, "/pb.Uploader/Upload", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploaderClient) GetFileInfo(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileInfo, error) {
	out := new(FileInfo)
	err := grpc.Invoke(ctx, "/pb.Uploader/GetFileInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Uploader service

type UploaderServer interface {
	// 文件上传
	Upload(context.Context, *UploadRequest) (*FileInfo, error)
	// 获取文件信息
	GetFileInfo(context.Context, *FileRequest) (*FileInfo, error)
}

func RegisterUploaderServer(s *grpc.Server, srv UploaderServer) {
	s.RegisterService(&_Uploader_serviceDesc, srv)
}

func _Uploader_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploaderServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Uploader/Upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploaderServer).Upload(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Uploader_GetFileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploaderServer).GetFileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Uploader/GetFileInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploaderServer).GetFileInfo(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Uploader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Uploader",
	HandlerType: (*UploaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _Uploader_Upload_Handler,
		},
		{
			MethodName: "GetFileInfo",
			Handler:    _Uploader_GetFileInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uploader.proto",
}

func init() { proto.RegisterFile("uploader.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xc1, 0x6a, 0xfa, 0x40,
	0x10, 0xc6, 0xdd, 0x98, 0x84, 0x38, 0xfa, 0xcf, 0x3f, 0x1d, 0x4a, 0x59, 0x0a, 0x85, 0x90, 0x53,
	0xa8, 0x90, 0x83, 0x7d, 0x82, 0x1c, 0x54, 0x02, 0xed, 0x65, 0xd1, 0xde, 0x13, 0x32, 0x26, 0x0b,
	0xd2, 0x6c, 0x75, 0xa5, 0xda, 0xa7, 0xe8, 0x23, 0x97, 0xdd, 0x58, 0xa1, 0x07, 0x6f, 0xbd, 0x7d,
	0xdf, 0x7c, 0xc3, 0xee, 0x6f, 0x66, 0x20, 0x3c, 0xa8, 0x6d, 0x57, 0xd6, 0xb4, 0xcb, 0xd4, 0xae,
	0xd3, 0x1d, 0x3a, 0xaa, 0x4a, 0x1a, 0xf8, 0xb7, 0xb6, 0x55, 0x41, 0xef, 0x07, 0xda, 0x6b, 0x0c,
	0xc1, 0x91, 0x35, 0x67, 0x31, 0x4b, 0x47, 0xc2, 0x91, 0xb5, 0xf1, 0x74, 0xe4, 0x4e, 0xef, 0xe9,
	0x88, 0x09, 0x78, 0xfa, 0xa4, 0x68, 0xc3, 0x87, 0x31, 0x4b, 0xc3, 0xd9, 0x24, 0x53, 0x55, 0xb6,
	0x90, 0x5b, 0x5a, 0x9d, 0x14, 0x89, 0x3e, 0x42, 0x04, 0xb7, 0x2e, 0x75, 0xc9, 0xdd, 0x98, 0xa5,
	0x13, 0x61, 0x75, 0xf2, 0x00, 0x63, 0xd3, 0x76, 0xe5, 0x9b, 0xe4, 0x8b, 0x41, 0x60, 0xf2, 0xe2,
	0x6d, 0xd3, 0xfd, 0x09, 0xc3, 0x2d, 0x78, 0x1f, 0xb2, 0xd6, 0xad, 0x85, 0xf0, 0x44, 0x6f, 0xf0,
	0x0e, 0xfc, 0x96, 0x64, 0xd3, 0x6a, 0xee, 0xd9, 0xf2, 0xd9, 0x19, 0xe2, 0xbd, 0xfc, 0x24, 0xee,
	0xc7, 0x2c, 0x1d, 0x0a, 0xab, 0x1f, 0xa7, 0x3d, 0x91, 0x79, 0x14, 0x47, 0xe0, 0x15, 0x2f, 0xf9,
	0x72, 0x1e, 0x0d, 0x10, 0xc0, 0xcf, 0x5f, 0xf3, 0x55, 0x2e, 0x22, 0x86, 0x01, 0xb8, 0x8b, 0xe2,
	0x79, 0x1e, 0x39, 0xb3, 0x06, 0x82, 0xf5, 0x79, 0xbb, 0x38, 0x05, 0xbf, 0xd7, 0x78, 0x63, 0xc8,
	0x7e, 0xed, 0xf7, 0xfe, 0x02, 0x6b, 0x26, 0x4d, 0x06, 0x98, 0xc1, 0x78, 0x49, 0xfa, 0x32, 0xfa,
	0xff, 0x9f, 0xf8, 0x4a, 0x7f, 0xe5, 0xdb, 0xdb, 0x3d, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x6d,
	0x31, 0xb3, 0x9a, 0xcd, 0x01, 0x00, 0x00,
}
